# Generated by Django 5.2.6 on 2025-09-17 06:25

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydata',
            name='category',
            field=models.CharField(choices=[('heritage_site', 'Heritage Site'), ('tourist_place', 'Tourist Place'), ('traditional_shop', 'Traditional Shop'), ('festival', 'Festival'), ('food', 'Food & Cuisine')], default='heritage_site', max_length=50),
        ),
        migrations.AlterField(
            model_name='communitydata',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='community_images'),
        ),
        migrations.AlterField(
            model_name='stateculture',
            name='festival_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='festival_images'),
        ),
    ]
