# Generated by Django 5.2.6 on 2025-09-17 06:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_communitydata_category_alter_communitydata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_details',
            name='state_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='state_images'),
        ),
    ]
