# Generated by Django 5.2.6 on 2025-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_state_details_state_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_details',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
