# Generated by Django 5.2.6 on 2025-09-17 09:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_state_details_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateculture',
            name='music_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='state_music/'),
        ),
    ]
