# Generated by Django 5.2.6 on 2025-09-17 10:14

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_stateculture_music_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='festival_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivals', to='app1.state_details')),
            ],
        ),
        migrations.CreateModel(
            name='StateMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('music_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='raw'), upload_to='state_music/')),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='app1.state_details')),
            ],
        ),
        migrations.DeleteModel(
            name='StateCulture',
        ),
    ]
