# Generated by Django 5.2.6 on 2025-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_statefestival_statemusic_delete_stateculture'),
    ]

    operations = [
        migrations.AddField(
            model_name='statefestival',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
